# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --production=false

# Copy source
COPY . .

# Build TypeScript to JavaScript
RUN npm run build

# Default command
CMD ["node", "build/index.js"]
